fr:
  languageName: FR
  contentDir: content/fr
  weight: 10
  params:
    languageISO: FR
    languageTag: fr-FR
    footer:
      Ce travail a bénéficié d’une aide de l’Etat gérée par l’Agence Nationale
      de la Recherche au titre de France 2030 portant la référence
      ANR-22-PEXD-0015
    alertText: <a class="alert-link stretched-link fw-normal"
      href="/news/diadem-ia-numpex/">Quand l'IA et le HPC rencontrent la Science des Matériaux, le 18 Novembre à Paris !</a>
    docSidebarRef: /documentation/use/ask-help
    docSidebarText: Contacter le support
en:
  languageName: EN
  contentDir: content/en
  weight: 20
  params:
    languageISO: EN
    languageTag: en-US
    footer:
      This work was supported by a grant from the French government managed by
      the National Research Agency under the France 2030 program with reference
      ANR-22-PEXD-0015.
    alertText: <a class="alert-link stretched-link fw-normal"
      href="/en/news/diadem-ia-numpex/">When AI and HPC meet Materials Science, on November 18 in Paris!</a>
    description: Digital platform for PEPR DIADEM
    docSidebarRef: /en/documentation/use/ask-help
    docSidebarText: Contact the support
