[fr]
  languageName = "FR"
  contentDir = "content/fr"
  weight = 10
  [fr.params]
    languageISO = "FR"
    languageTag = "fr-FR"
    footer = 'Ce travail a bénéficié d’une aide de l’Etat gérée par l’Agence Nationale de la Recherche au titre de France 2030 portant la référence ANR-22-PEXD-0015'
    alertText = '<a class="alert-link stretched-link fw-normal" href="/blog/example-post/">Doks version 1.0 just shipped!</a>'


[en]
  languageName = "EN"
  contentDir = "content/en"
  weight = 20
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    footer = 'This work was supported by a grant from the French government managed by the National Research Agency under the France 2030 program with reference ANR-22-PEXD-0015.'
    alertText = '<a class="alert-link stretched-link fw-normal" href="/blog/example-post/">Doks version 1.0 just shipped!</a>'
    description = "Digital platform for PEPR DIADEM"
#[de]
#  languageName = "German"
#  contentDir = "content/de"
#  weight = 15
#  [de.params]
#    languageISO = "DE"
#    languageTag = "de-DE"
#    footer = 'Gebaut mit <a class="text-muted" href="https://gethyas.com/">Hyas</a>'
#    alertText = 'Neue Version ist da! <a class="alert-link stretched-link" href="https://getdoks.org/blog/doks-v0.5/">Doks v0.5</a>'

#[nl]
#  languageName = "Nederlands"
#  contentDir = "content/nl"
#  weight = 20
#  [nl.params]
#    languageISO = "NL"
#    languageTag = "nl-NL"
#    titleAddition = "Modern documentatie-thema"
#    description = "Doks is een Hugo-thema waarmee je moderne documentatie-websites kunt bouwen die veilig, snel en klaar voor SEO zijn — standaard."
#    titleHome = "Doks thema"
#    footer = 'Mogelijk gemaakt door <a href="https://www.netlify.com/">Netlify</a>, <a href="https://gohugo.io/">Hugo</a>, en <a href="https://getdoks.org/">Doks</a>'
#    alertText = 'Introductie van het Doks-kinderthema, verschillende DX + UX-updates en meer! <a class="alert-link stretched-link" href="https://getdoks.org/blog/doks-v0.2/">Bekijk Doks v0.2</a>'
