title: DIAMOND
description: Plateforme numérique du PEPR DIADEM
images:
  - /cover-diamond.png
mainSections:
  - about
  - codes
  - documentation
  - workflows
diamond:
  enableNews: true
social:
  twitter: ""
doks:
  colorMode: auto
  colorModeToggler: true
  navbarSticky: true
  containerBreakpoint: fluid
  navBarButton: false
  navBarButtonUrl: /docs/prologue/introduction/
  navBarButtonText: Demander de l'aide
  flexSearch: true
  searchExclKinds: []
  searchExclTypes:
    - blog
  showSearch: []
  indexSummary: false
  showDate: false
  showSummary: true
  searchLimit: 99
## Used as banner for news
  alert: true
  alertDismissable: false
##
  bootstrapJavascript: false
  sectionNav:
    - codes
    - documentation
    - workflows
  toTopButton: true
  breadcrumbTrail: false
  headlineHash: false
  scrollSpy: true
  multilingualMode: true
  showMissingLanguages: true
  docsVersioning: false
  docsVersion: "1.0"
  headerBar: true
  backgroundDots: false
  sectionFooter: false
  relatedPosts: false
  imageList: true
  imageSingle: false
  editPage: false
  lastMod: false
  repoHost: GitHub
  docsRepo: https://github.com/h-enk/doks
  docsRepoBranch: main
  docsRepoSubPath: ""
  menu:
    section:
      auto: true
      collapsibleSidebar: true
render_hooks:
  image:
    errorLevel: ignore
  link:
    errorLevel: ignore
    highlightBroken: false
thulite_images:
  landscape:
    normalize: 1360x765
    lqip: 16x9
    widths:
      - 480
      - 640
      - 800
      - 1024
  portrait:
    normalize: 765x1360
    lqip: 9x16
    widths:
      - 480
      - 640
      - 800
      - 1024
inline_svg:
  iconSetDir: tabler-icons
seo:
  title:
    separator: " | "
    suffix: ""
  favicons:
    sizes: []
    icon: favicon.png
    svgIcon: favicon.svg
    maskIcon: mask-icon.svg
    maskIconColor: white
  schemas:
    type: Organization
    logo: favicon-512x512.png
    name: Hyas
    sameAs: []
    images:
      - /cover-diamond.png
    article: []
    newsArticle: []
    blogPosting:
      - blog
    product: []
math: true
