# https://gitlab.com/pages/hugo/-/blob/main/.gitlab-ci.yml
image: registry.gitlab.com/pages/hugo/hugo_extended:latest
###image: registry.gitlab.com/pages/hugo/hugo_extended:0.100.2

variables:
  HUGO_ENV: production

default:
  before_script:
    - apk add --no-cache git go npm brotli
    - npm install postcss-cli autoprefixer --save-dev
    - npm install @hyas/doks-core@latest --save-dev
    - npm install --save-dev
    # https://www.npmjs.com/package/hugo-extended


test:  # builds and tests your site
  script:
    - hugo
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH

pages:  # a predefined job that builds your pages and saves them to the specified path.
  script:
    - hugo
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_MESSAGE =~ /^\[publish\].*/i
  environment: production

