image: node:20

stages:
  - deploy

variables:
  HUGO_VERSION: "0.140.0"
  HUGO_ENVIRONMENT: next
  HUGO_ENV: next
  NODE_ENV: production

pages:
  stage: deploy
  before_script:
    - apt-get update -y && apt-get install -y wget ca-certificates
    - wget -q -O hugo.deb "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb"
    - dpkg -i hugo.deb
    - npm ci
  script:
    - npm run build
  artifacts:
    paths:
      - public
  only:
<<<<<<< HEAD
    - staging
=======
    - staging
>>>>>>> e0936615 (Update gitlab-ci.yml)
