# Default config
tabWidth: 4
endOfLine: lf
singleQuote: true
printWidth: 120
trailingComma: none
bracketSameLine: true
quoteProps: consistent

# Overrided config
overrides:
  - files: ["*.md", "*.json", "*.yaml"]
    options:
      tabWidth: 2
      singleQuote: false
  - files: ["*.scss"]
    options:
      singleQuote: false
