main:
  - name: Codes
    url: codes/home/
    weight: 10
  - name: Workflows
    url: workflows/
    weight: 20
  - name: Documentation
    url: documentation/home/
    weight: 30
  - name: Données
    url: data/
    weight: 40
  - name: Contact
    url: contact/
    weight: 50
  - name: À propos
    url: about/diamond/
    weight: 60
    identifier: about-fr

# codes:
#     - name: Codes
#       weight: 10
#       identifier: codes-fr
#       parent: ""
#       url: fr/codes/
#     - name : Scientific computing
#       weight : 10
#       identifier: scientific-computing-fr
#       parent: codes-fr
#       url: fr/codes/scientific-computing/
#     - name : Visualisation
#       weight : 20
#       identifier: visualisation-fr
#       parent: codes-fr
#       url: fr/codes/visualisation/

# docs:
#   - name: À propos
#     url: fr/about/
#     weight: 10
#   - name: Codes
#     url: fr/codes/
#     weight: 20
#   - name: Workflows
#     url: fr/workflows/
#     weight: 30
#   - name: Données
#     url: fr/data/
#     weight: 40
#   - name: Documentation
#     url: fr/documentation/
#     weight: 50

# docs:
#   - name: DIADEM
#     weight: 10
#     identifier: diadem-fr
#     url: fr/about/diadem/
#   - name: Conteneurs
#     weight: 20
#     identifier: containers-fr
#     url: fr/about/containers/
#   - name: DIADEM
#     weight: 30
#     identifier: apptainer-fr
#     url: fr/about/apptainer/
