main:
  - name: Codes
    url: en/codes/
    weight: 10
  - name: Workflows
    url: en/workflows/
    weight: 20
  - name: Documentation
    url: en/documentation/
    weight: 30
  - name: Data
    url: en/data/
    weight: 40
  - name: Contact
    url: en/contact/
    weight: 50
  - name: About
    url: en/about/diamond/
    weight: 60
    identifier: about-en
