main:
  - name: About
    url: en/about/
    weight: 10
  - name: Codes
    url: en/codes/
    weight: 20
  - name: Workflows
    url: en/workflows/
    weight: 30
  - name: Data
    url: en/data/
    weight: 40
  - name: Documentation
    url: en/docs/
    weight: 50
  - name: News
    url: en/news/
    weight: 60
  - name: Contact
    url: en/contact/
    weight: 70