name: Protect Critical Files

on:
  push:

jobs:
  check-protected-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch full history to handle multi-commit pushes

      - name: Fetch Remote Branch
        run: |
          TARGET_BRANCH=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
          echo "Target branch: $TARGET_BRANCH"

          # Ensure the latest state of the remote branch is fetched
          git fetch origin $TARGET_BRANCH

          # Debug: Show fetched branch information
          echo "Fetched branches:"
          git branch -r

      - name: Identify Commit Range
        id: commits
        run: |
          TARGET_BRANCH=$(echo $GITHUB_REF | sed 's/refs\/heads\///')

          # Ensure the remote branch reference exists
          git fetch origin $TARGET_BRANCH

          # Calculate the base commit as the last known state of the remote branch
          BASE_COMMIT="origin/$TARGET_BRANCH"
          echo "Base commit: $BASE_COMMIT"
          echo "Commit range: $BASE_COMMIT..HEAD"

          # Expose the base commit and range for subsequent steps
          echo "BASE_COMMIT=$BASE_COMMIT" >> $GITHUB_ENV

      - name: Check for Unauthorized Changes
        run: |
          # Define the protected files
          PROTECTED_FILES=("package.json" "package-lock.json")

          # Use the base commit from the environment
          COMMIT_RANGE="${BASE_COMMIT}..HEAD"
          echo "Checking commits in range: $COMMIT_RANGE"

          # Fetch the list of modified files in the range
          MODIFIED_FILES=$(git diff --name-only $COMMIT_RANGE)
          echo "Modified files in push: $MODIFIED_FILES"

          # Check if any protected files were modified
          for file in "${PROTECTED_FILES[@]}"; do
              if echo "$MODIFIED_FILES" | grep -q "^$file$"; then
                  echo "Error: Unauthorized modification detected in $file."
                  exit 1
              fi
          done

          echo "All protected files are safe."
