name: Protect Critical Files

on:
  push:

jobs:
  check-protected-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch full commit history to handle multi-commit pushes

      - name: Identify commit range
        id: range
        run: |
          # Ensure the remote branch state is available
          git fetch origin $(echo $GITHUB_REF | sed 's/refs\/heads\///')

          # Find the starting point of the push
          TARGET_BRANCH=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
          BASE_COMMIT=$(git merge-base origin/$TARGET_BRANCH HEAD)

          echo "Base commit: $BASE_COMMIT"
          echo "Commit range: $BASE_COMMIT..HEAD"

          # Output the commit range
          echo "BASE_COMMIT=$BASE_COMMIT" >> $GITHUB_ENV

      - name: Check for unauthorized changes
        run: |
          # Define the protected files
          PROTECTED_FILES=("package.json" "package-lock.json")

          # Get the base commit from the environment
          COMMIT_RANGE="${BASE_COMMIT}..HEAD"

          echo "Checking commits in range: $COMMIT_RANGE"

          # List all files modified in the range
          MODIFIED_FILES=$(git diff --name-only $COMMIT_RANGE)

          echo "Modified files in push: $MODIFIED_FILES"

          # Check if any protected files were modified
          for file in "${PROTECTED_FILES[@]}"; do
              if echo "$MODIFIED_FILES" | grep -q "^$file$"; then
                  echo "Error: Unauthorized modification detected in $file."
                  exit 1
              fi
          done

          echo "All protected files are safe."
