name: Protect Critical Files

on:
  push:

jobs:
  check-protected-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch full history to ensure all commits are available

      - name: Debug Repository State
        run: |
          echo "Git log:"
          git log --oneline --graph -n 10

          echo "Git status:"
          git status

          echo "Fetching remote branches..."
          git fetch origin

      - name: Identify Commit Range
        id: commits
        run: |
          TARGET_BRANCH=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
          echo "Target branch: $TARGET_BRANCH"

          # Ensure the latest branch state is fetched
          git fetch origin $TARGET_BRANCH

          # Find the base commit
          BASE_COMMIT=$(git merge-base origin/$TARGET_BRANCH HEAD)
          echo "Base commit: $BASE_COMMIT"
          echo "Commit range: $BASE_COMMIT..HEAD"

          # Expose variables for subsequent steps
          echo "BASE_COMMIT=$BASE_COMMIT" >> $GITHUB_ENV

      - name: Check for Unauthorized Changes
        run: |
          # Define the protected files
          PROTECTED_FILES=("package.json" "package-lock.json")

          # Use the commit range from the previous step
          COMMIT_RANGE="${BASE_COMMIT}..HEAD"
          echo "Checking commits in range: $COMMIT_RANGE"

          # Fetch the list of modified files
          MODIFIED_FILES=$(git diff --name-only $COMMIT_RANGE)
          echo "Modified files in push: $MODIFIED_FILES"

          # Check if any protected files were modified
          for file in "${PROTECTED_FILES[@]}"; do
              if echo "$MODIFIED_FILES" | grep -q "^$file$"; then
                  echo "Error: Unauthorized modification detected in $file."
                  exit 1
              fi
          done

          echo "All protected files are safe."
