name: Protect Package Files

on:
  push:

jobs:
  check-protected-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all commits in the branch

      - name: Check for unauthorized changes
        run: |
          # Define the protected files
          PROTECTED_FILES=("package.json" "package-lock.json")

          # Get the range of commits included in the push
          COMMIT_RANGE=$(git rev-parse origin/$(echo $GITHUB_REF | sed 's/refs\/heads\///')^)..HEAD

          echo "Checking commits in range: $COMMIT_RANGE"

          # Fetch the list of modified files in the range of commits
          MODIFIED_FILES=$(git diff --name-only $COMMIT_RANGE)

          echo "Modified files in push: $MODIFIED_FILES"

          # Check if any protected files were modified
          for file in "${PROTECTED_FILES[@]}"; do
              if echo "$MODIFIED_FILES" | grep -q "^$file$"; then
                  echo "Error: Unauthorized modification detected in $file."
                  exit 1
              fi
          done

          echo "All protected files are safe."
