name: Protect Critical Files

on:
  push:

jobs:
  check-protected-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2 # Ensure we fetch at least the last 2 commits

      - name: Check for unauthorized changes
        run: |
          # Define the protected files
          PROTECTED_FILES=("package.json" "package-lock.json")

          # Fetch the list of modified files in the latest push
          MODIFIED_FILES=$(git diff --name-only HEAD~1 HEAD)

          # Check if any protected files were modified
          for file in "${PROTECTED_FILES[@]}"; do
              if echo "$MODIFIED_FILES" | grep -q "^$file$"; then
                  echo "Error: Unauthorized modification detected in $file."
                  exit 1
              fi
          done

          echo "All protected files are safe."
