name: Protect Critical Files

on:
  push:
    paths:
      - 'package.json'
      - 'package-lock.json'

jobs:
  check-protected-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check for unauthorized changes
        run: |
          # Define the protected files
          PROTECTED_FILES=("package.json" "package-lock.json")

          # Loop through each protected file
          for file in "${PROTECTED_FILES[@]}"; do
              if git diff-tree --no-commit-id --name-only -r HEAD | grep -q "^${file}$"; then
                  echo "Error: Unauthorized modification detected in ${file}."
                  exit 1
              fi
          done

          echo "All protected files are safe."
