name: Test Github action email sending

on:
  workflow_dispatch:

jobs:
  test-email:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          # Specify connection via URL (replaces server_address, server_port, secure,
          # username and password)
          #
          # Format:
          #
          #  * smtp://user:password@server:port
          #  * smtp+starttls://user:password@server:port
          # connection_url: # ${{secrets.MAIL_CONNECTION}}
          # Required mail server address if not connection_url:
          server_address: smtp.gmail.com
          # Server port, default 25:
          server_port: 465
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional (recommended) mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: \[diamond-diadem.github.io\] - Push rejected - Modified protected files
          # Required recipients' addresses:
          to: david.martin-calle@univ-lyon1.fr # ${{ github.event.pusher.email }}
          # Required sender full name (address can be skipped):
          from: DIAMOND website administration # <user@example.com>
          # Optional plain body:
          body: Hello,\n\nYour push to the repository '${{ github.repository }}' was rejected because it included unauthorized changes to protected files (e.g., package.json or package-lock.json).\n\nPlease review the repository guidelines and adjust your changes before pushing again.\n\nThank you.
          # Optional HTML body read from file:
          html_body:
          # Optional carbon copy recipients:
          cc:
          # Optional blind carbon copy recipients:
          bcc:
          # Optional recipient of the email response:
          reply_to:
          # Optional Message ID this message is replying to:
          in_reply_to:
          # Optional unsigned/invalid certificates allowance:
          ignore_cert: true
          # Optional converting Markdown to HTML (set content_type to text/html too):
          convert_markdown: true
          # Optional attachments:
          attachments:
          # Optional priority: 'high', 'normal' (default) or 'low'
          priority: high
          # Optional nodemailerlog: true/false
          nodemailerlog: false
          # Optional nodemailerdebug: true/false if true lognodem will also be set true
          nodemailerdebug: false
