name: Test Github action email sending

on:
  workflow_dispatch:

jobs:
  test-email:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtpbv.univ-lyon1.fr
          server_port: 587
          username: david.martin-calle@univ-lyon1.fr
          password: ${{secrets.MAIL_PASSWORD}}
          subject: "[diamond-diadem.github.io] - Push rejected - Modified protected files"
          to: david.martin-calle@univ-lyon1.fr
          from: DIAMOND website automatic mail
          html_body: "Bonjour,<br><br>Votre push vers le dépôt '${{ github.repository }}' a été refusé car il incluait des modifications non autorisées dans des fichiers protégés (package.json et/ou package-lock.json).<br><br>Merci.<br><hr><br>Hello,<br><br>Your push to the repository '${{ github.repository }}' was rejected because it included unauthorized changes to protected files (package.json and/or package-lock.json).<br><br>Thank you."
          priority: high
